from datetime import date
from decimal import Decimal
from typing import Protocol


class ForecastReader(Protocol):
    def active_accounts(self, user_id: int) -> list[dict]: ...
    def balances(self, user_id: int, as_of: date) -> dict[int, Decimal]: ...
    def reservations(self, user_id: int) -> list[dict]: ...
    def pending_movements(self, user_id: int, start: date, end: date) -> list[dict]: ...
