from datetime import date
from decimal import Decimal
from typing import Protocol


class SavingsStore(Protocol):
    def today(self, user_id: int) -> date: ...
    def account(self, user_id: int, account_id: int, lock: bool = False) -> dict | None: ...
    def account_balance(self, user_id: int, account_id: int) -> Decimal: ...
    def goals(self, user_id: int) -> list[dict]: ...
    def goal(self, user_id: int, goal_id: int) -> dict | None: ...
    def funded(self, goal_id: int) -> Decimal: ...
    def add_goal(self, user_id: int, values: dict) -> dict: ...
    def update_goal(self, user_id: int, goal_id: int, changes: dict) -> dict: ...
    def reservations(self, user_id: int) -> list[dict]: ...
    def reservation(self, user_id: int, reservation_id: int, lock: bool = False) -> dict | None: ...
    def reserved_on_account(self, account_id: int) -> Decimal: ...
    def reservation_for(self, user_id: int, account_id: int, goal_id: int | None) -> dict | None: ...
    def set_reservation(self, user_id: int, account_id: int, goal_id: int | None, amount: Decimal) -> dict: ...
    def add_contribution(self, user_id: int, goal_id: int, account_id: int, day: date, amount: Decimal, notes: str | None) -> None: ...
    def contributions(self, user_id: int) -> list[dict]: ...
    def rules(self, user_id: int) -> list[dict]: ...
    def rule(self, user_id: int, rule_id: int) -> dict | None: ...
    def source(self, user_id: int, source_id: int) -> dict | None: ...
    def sources(self, user_id: int) -> list[dict]: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def add_rule(self, user_id: int, values: dict) -> dict: ...
    def update_rule(self, user_id: int, rule_id: int, changes: dict) -> dict: ...
    def delete_rules_for_source(self, user_id: int, source_id: int) -> None: ...
    def commit(self) -> None: ...


class SavingsRuleCleanup(Protocol):
    def delete_rules_for_source(self, user_id: int, source_id: int) -> None: ...
