from typing import Protocol


class IdentityStore(Protocol):
    def user_by_email(self, email: str) -> dict | None: ...
    def user(self, user_id: int) -> dict | None: ...
    def users(self) -> list[dict]: ...
    def create_user(self, email: str, password_hash: str) -> dict: ...
    def change_password(self, user_id: int, password_hash: str) -> dict: ...
    def photo(self, user_id: int) -> dict | None: ...
    def save_photo(self, user_id: int, content_type: str, data: bytes) -> dict: ...
    def delete_photo(self, user_id: int) -> None: ...
    def settings(self, user_id: int) -> dict: ...
    def update_settings(self, user_id: int, changes: dict) -> dict: ...


class Credentials(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...
    def token(self, user_id: int, auth_version: int) -> str: ...
