from datetime import date
from decimal import Decimal
from typing import Protocol


class DashboardReader(Protocol):
    def today(self, user_id: int) -> date: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def balances(self, user_id: int, day: date) -> dict[int, Decimal]: ...
    def reservations(self, user_id: int) -> list[dict]: ...
    def categories(self, user_id: int) -> list[dict]: ...
    def expenses(self, user_id: int, start: date, end: date) -> list[dict]: ...
    def recent(self, user_id: int) -> list[dict]: ...
