"""Persistence contract used by ledger use cases."""

from datetime import date
from decimal import Decimal
from typing import Protocol


class LedgerStore(Protocol):
    def today(self, user_id: int) -> date: ...
    def account(self, user_id: int, account_id: int) -> dict | None: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def category(self, user_id: int, category_id: int) -> dict | None: ...
    def categories(self, user_id: int) -> list[dict]: ...
    def cleared_movements(self, user_id: int, as_of: date) -> list[dict]: ...
    def transaction(self, user_id: int, transaction_id: int) -> dict | None: ...
    def transactions(self, user_id: int, filters: dict, page: int, page_size: int) -> tuple[list[dict], int]: ...
    def sibling_category(self, user_id: int, name: str, parent_id: int | None, exclude_id: int | None) -> bool: ...
    def has_child_categories(self, category_id: int) -> bool: ...
    def add_account(self, user_id: int, values: dict) -> dict: ...
    def update_account(self, user_id: int, account_id: int, changes: dict) -> dict: ...
    def add_category(self, user_id: int, values: dict) -> dict: ...
    def update_category(self, user_id: int, category_id: int, changes: dict) -> dict: ...
    def delete_category(self, user_id: int, category_id: int) -> None: ...
    def add_transaction(self, user_id: int, values: dict) -> dict: ...
    def update_transaction(self, user_id: int, transaction_id: int, changes: dict) -> dict: ...
    def delete_transaction(self, user_id: int, transaction_id: int) -> None: ...


class LedgerPolicies(Protocol):
    """Cross-domain facts needed before ledger writes."""

    def linked_transaction(self, transaction_id: int) -> bool: ...
    def investment_cost(self, user_id: int, account_id: int) -> Decimal: ...
    def account_references(self, user_id: int, account_id: int) -> tuple[bool, bool, bool]: ...
    def category_references(self, category_id: int) -> bool: ...


class LedgerRead(Protocol):
    """Ledger data shared with read models in other domains."""

    def today(self, user_id: int) -> date: ...
    def account(self, user_id: int, account_id: int) -> dict | None: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def category(self, user_id: int, category_id: int) -> dict | None: ...
    def balance(self, user_id: int, account_id: int, as_of: date | None = None) -> Decimal: ...
    def balances(self, user_id: int, as_of: date | None = None) -> dict[int, Decimal]: ...
