from datetime import date
from decimal import Decimal
from typing import Protocol


class InvestmentStore(Protocol):
    def today(self, user_id: int) -> date: ...
    def account(self, user_id: int, account_id: int) -> dict | None: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def balances(self, user_id: int) -> dict[int, Decimal]: ...
    def positions(self, user_id: int) -> list[dict]: ...
    def position(self, user_id: int, position_id: int) -> dict | None: ...
    def allocated_cost(self, user_id: int, account_id: int, exclude_id: int | None) -> Decimal: ...
    def add_position(self, user_id: int, values: dict) -> dict: ...
    def update_position(self, user_id: int, position_id: int, changes: dict) -> dict: ...
    def delete_position(self, user_id: int, position_id: int) -> None: ...
    def transaction(self, user_id: int, transaction_id: int) -> dict | None: ...
    def contribution_for_transaction(self, transaction_id: int) -> bool: ...
    def contributions(self, user_id: int) -> list[dict]: ...
    def contribution(self, user_id: int, contribution_id: int) -> dict | None: ...
    def add_contribution(self, user_id: int, account_id: int, transaction_id: int) -> dict: ...
    def delete_contribution(self, user_id: int, contribution_id: int) -> None: ...
    def debts(self, user_id: int) -> list[dict]: ...
    def snapshots(self, user_id: int) -> list[dict]: ...
    def snapshot_exists(self, user_id: int, day: date) -> bool: ...
    def add_snapshots(self, user_id: int, day: date, currencies: list[dict]) -> list[dict]: ...
