from typing import Protocol


class ImportStore(Protocol):
    def job(self, user_id: int, job_id: int) -> dict | None: ...
    def jobs(self, user_id: int) -> list[dict]: ...
    def rows(self, job_id: int, sheet_name: str | None = None, limit: int | None = None) -> list[dict]: ...
    def create_job(self, user_id: int, values: dict, sheets: dict) -> dict: ...
    def update_job_and_rows(self, user_id: int, job_id: int, changes: dict, rows: list[dict]) -> dict: ...
    def delete_job(self, user_id: int, job_id: int) -> None: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def categories(self, user_id: int) -> list[dict]: ...
    def existing_keys(self, user_id: int, keys: list[str]) -> set[str]: ...
    def lock_user(self, user_id: int) -> None: ...
    def add_imported_movement(self, user_id: int, values: dict, key: str) -> int: ...
    def investment_costs(self, user_id: int) -> dict[int, object]: ...
    def balances(self, user_id: int) -> dict: ...
    def transactions(self, user_id: int) -> list[dict]: ...
