from decimal import Decimal
from typing import Protocol


class DebtReader(Protocol):
    def debt_remaining(self, user_id: int, debt_id: int, principal: Decimal) -> Decimal: ...


class PlanningReader(Protocol):
    def accounts(self, user_id: int) -> list[dict]: ...
    def income_sources(self, user_id: int) -> list[dict]: ...
    def income_receipt_dates(self, source_id: int) -> set: ...
    def recurring_expenses(self, user_id: int) -> list[dict]: ...
    def recurring_payment_dates(self, expense_id: int) -> set: ...
    def scheduled_expenses(self, user_id: int, end) -> list[dict]: ...
    def debts(self, user_id: int) -> list[dict]: ...
    def debt_remaining(self, user_id: int, debt_id: int, principal: Decimal) -> Decimal: ...
