from datetime import date
from decimal import Decimal
from typing import Protocol


class PlanningStore(Protocol):
    def today(self, user_id: int) -> date: ...
    def account(self, user_id: int, account_id: int) -> dict | None: ...
    def category(self, user_id: int, category_id: int) -> dict | None: ...
    def get(self, kind: str, user_id: int, item_id: int) -> dict | None: ...
    def list(self, kind: str, user_id: int) -> list[dict]: ...
    def create(self, kind: str, user_id: int, values: dict, commit: bool = True) -> dict: ...
    def update(self, kind: str, user_id: int, item_id: int, changes: dict, commit: bool = True) -> dict: ...
    def delete(self, kind: str, user_id: int, item_id: int) -> None: ...
    def delete_related(self, kind: str, user_id: int, field: str, value: int) -> None: ...
    def exists(self, kind: str, field: str, value, extra: dict | None = None) -> bool: ...
    def linked_any(self, transaction_id: int) -> bool: ...
    def debt_remaining(self, user_id: int, debt_id: int, principal: Decimal) -> Decimal: ...
    def clear_other_primary(self, user_id: int, selected_id: int) -> None: ...
    def commit(self) -> None: ...
