from datetime import date
from typing import Protocol


class BudgetStore(Protocol):
    def today(self, user_id: int) -> date: ...
    def category(self, user_id: int, category_id: int) -> dict | None: ...
    def categories(self, user_id: int) -> list[dict]: ...
    def accounts(self, user_id: int) -> list[dict]: ...
    def budgets(self, user_id: int) -> list[dict]: ...
    def budget(self, user_id: int, budget_id: int) -> dict | None: ...
    def add_budget(self, user_id: int, values: dict) -> dict: ...
    def update_budget(self, user_id: int, budget_id: int, changes: dict) -> dict: ...
    def actuals(self, user_id: int, start: date, end: date) -> list[dict]: ...
